# Generated by Django 5.2.7 on 2025-11-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_alter_user_password_hash_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
