# Generated by Django 5.2.7 on 2025-11-05 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessCheck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'authorization_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Разрешение',
                'verbose_name_plural': 'Разрешения',
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accessCheck.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accessCheck.role')),
            ],
            options={
                'verbose_name': 'Связь роль-разрешение',
                'verbose_name_plural': 'Связи роль-разрешения',
                'db_table': 'role_permission',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(help_text='Связь с ролью', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accessCheck.role')),
                ('user', models.ForeignKey(help_text='Связь с пользователем', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accessCheck.user')),
            ],
            options={
                'verbose_name': 'Связь пользователь-роль',
                'verbose_name_plural': 'Связи пользователь-роли',
                'db_table': 'user_role',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
